SITE:
    Local: '127.0.0.1:8888'
    Remote:
        Url: 'https://peildo.ca'
        Path: user
PORT: 8000
BSREWRITE:
    Css:
        Match: "/sites/peildo.ca/themes/ia_peildo/css/"
        Replace: "/css/"
    Js:
        Match: "/sites/peildo.ca/themes/ia_peildo/js/"
        Replace: "/js/"
PATHS:
    Watch:
      #changes in these compiled files trigged reload
      - ./css/*.css
      - ./js/*.js
    Scss:
        Dir: css/src
        #FileName: app.scss
        Libraries:
            - css/src/libraries/guff
            #- css/libraries/typeplate
    Css:
        Dir: css
        #FileName: app.css
    Js:
        Src: ./js/src/*.js
        Dest: js
        FileName: 'peildo.behaviors.js'
    Img:
        Src: images/src
        Dest: images

